### ISSUE TITLE
Jobs to search Base Unica for organizations & upload response to Salesforce

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/itau-social#1]
## Background, context, and business value

We're helping Vera Solutions partner, Itaú Social, integrate Salesforce with the external system they use, Base Unica, to look-up in Base Unica, registered accounts entered into Salesforce. The desired use cases are as follows:

- As a Salesforce user, I want to create a new account record in Sales Force and automatically check whether an organization has already been created in the Base Unica data system, so that I can avoid entering duplicate or incorrect organization / account data.

- As a Salesforce user, I want for corresponding account data in Base Unica to autopopulate mapped out Salesforce fields.

## The specific request, in as few words as possible

Goal is to create a semi-automated process in Salesforce that looks up account information in Base Unica via a reference 'cnpj' and then autopopulates Base Unica account information into the correspondingly mapped fields in the Salesforce account. This should include: 
1. Job that is triggered by message filter that will send a GET request to `GET https://hhh.baseunica.itausocial.org.br/api/cnpj/{cnpj}`
2. Job that upserts Salesforce `Account` data based on the response received from Base Unica in step 1

[See here](https://docs.google.com/spreadsheets/d/1PX9ZgA0OeC8Bf0dT78S8DB5c1ilj5QOhekZTZXN2Ffw/edit?usp=sharing) for the "Data Flows" (sheet 1) and the "Mappings FOR Base Unica to SF" (sheet 2).

[See here](https://docs.google.com/document/d/10_QVvfGJRxw-uJXfGbgo1s7X3p1lR1byWQ9bMfzDk1U/edit) for the Base Unica API docs (see `Section 2. Search CNPJ`). 

## state.json
Salesforce will send `sample_data/payload.json` to the OpenFn inbox. This should trigger job 1 to fetch data from Base Unica. 

1. Base Unica: Itau Social Base Unica Credentials can be found in lastpass by searching "Base Unica Testing (Itau Social)"
2. Salesforce sandbox: See LP for "Itau Social Salesfoce"

## adaptor
1. Use `language-http` to access BU
2. Then use `language-salesforce`

## expression.js

When new `Account` created is Salesforce, a new outbound message will be sent to OpenFn with `organization_Id` and `cnpj`... 

1. OpenFn will send GET request to search Base Unica for `cnpj`

2. If match found, Base Única will respond with the organization information captured in BU (see "Response" body in section 2 in the API documentation). You may need to clean the `CNPJ__c` value received from Salesforce to remove any special characters (`.`, `-`, or `/`).
`"CNPJ__c": "77.054.497/0001-54"` --> `77054497000154`

2.1. OpenFn will update the triggering Salesforce `Account` record via the externalId `CNPJ__c` with the Base Unica information from the response [(see mapping specs)](https://docs.google.com/spreadsheets/d/1PX9ZgA0OeC8Bf0dT78S8DB5c1ilj5QOhekZTZXN2Ffw/edit?usp=sharing) . 

2.2. If no match found in Base Única, the API will search the Receita Federal’s API (Brazilian IRS) and create a new organization record within BU (this is the default API behavior - see section 2 in the API documentation). OpenFn will still update the triggering Salesforce `Account` record, but there may be less data to map. 

2.3. If we receive a 400 response from Base Unica, can we still update the Salesforce Account record? However the only mapping should be to update Account `Sync_Status__c` to `'Falha'` to indicate that the sync failed.

## output.json

Update the Salesforce `Account` record via the external Id `CNPJ__c` using the mapping specs. 
Note: the field mappings may differ/ certain values may not be defined depending on Base Unica's response. 

## Toggl
You can log your time to the 'Itau Social' project.

**Comment by aleksa-krolls** [comment]
@lakhassane Both @jedbgold and I will be supporting you on this one. Note that there might be some minor changes in the Base Unica --> Salesforce mappings, so please build to the spec for now.

**Comment by aleksa-krolls** [comment]
@lakhassane updated the credential and the base URL for base unica to direct to the testing environment

**Comment by lakhassane** [comment]
@jedbgold @aleksa-krolls considering `2.2` what will be recorded in SF. From what I see fetching the IRS will return arrays of value for each field.

Also can you check if the token is valid to use for this API fetch (in IRS). Does not seem to be valid on my side.

**Comment by aleksa-krolls** [comment]
@lakhassane To answer your questions...
1. I get a `200` response if I specify the token as bearer: `'Authorization: Bearer 54Zhxxxxxxxxxxx' . 
2. The mappings for `2.2` will be the same as `2.1`. However, we anticipate that there will be fewer fields present in the response body for `2.2` (therefore many of these mappings will be undefined). 

Then a couple of new requests that I will also document in the above issue...
3. I'm seeing in the API docs that `CNPJ` does not have any special characters by is an integer string. Therefore can you please add transformation logic to clean the value received from Salesforce to remove any special characters (`.`, `-`, or `/`). 
`"CNPJ__c": "77.054.497/0001-54"` --> `77054497000154`
4. If we receive a `400` response from Base Unica, can we still update the Salesforce `Account` record? However the only mapping should be to update Account `Sync_Status__c` to `'Falha'` to indicate that the sync failed.

**Comment by aleksa-krolls** [comment]
@lakhassane What does `state.configuration` need to look like for this job to successfully run? (Can you please share with the real credential values redacted?)

**Comment by lakhassane** [comment]
@aleksa-krolls it should be:
```
{
  "configuration": {
    "token": []
  },
  "data": {
  }
}
```

**Comment by jedbgold** [comment]
@lakhassane we have added a transformation rule to row 4 `cnpj` to `CNPJ_c` on the [data mappings sheet](https://docs.google.com/spreadsheets/d/1PX9ZgA0OeC8Bf0dT78S8DB5c1ilj5QOhekZTZXN2Ffw/edit#gid=1182083213). Please take a look and let me know if it makes sense to you.

**Comment by lakhassane** [comment]
Yes definitely @jedbgold. I got it

**Comment by jedbgold** [comment]
Thanks @lakhassane . Also, please take a look at `row 24` on the [data mappings sheet](https://docs.google.com/spreadsheets/d/1PX9ZgA0OeC8Bf0dT78S8DB5c1ilj5QOhekZTZXN2Ffw/edit#gid=1182083213). We need for all of the output letters to be lower-case.

**Comment by jedbgold** [comment]
@lakhassane please take a look at `row 30` transformation rule on the [data mappings sheet](https://docs.google.com/spreadsheets/d/1PX9ZgA0OeC8Bf0dT78S8DB5c1ilj5QOhekZTZXN2Ffw/edit#gid=1182083213). Let me know if it's now clear. Sorry for the confusion there.

**Comment by lakhassane** [comment]
No confusion @jedbgold it's pretty clear and implemented :)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane I'm realizing this solution setup makes it very hard to reprocess failures when job `02` fails... because the user needs to find the matching Message for job `01` and then re-run. For example... how could you easily re-run [this failure](https://www.openfn.org/projects/2983/runs/10232377)?

Would it be possible to modify this so that job `01` sends the final state as a new Message to the OpenFn Inbox? We will then configure job `02` to run on a Message Filter trigger. Thoughts? (And please advise on how we should change the `configuration` if we implement this job `01` change?

**Comment by lakhassane** [comment]
@aleksa-krolls, stuck on a conceptual issue here.
Getting job `01` to send final state to OpenFn inbox would be pretty straighforward since we will use the same `language-http`
However job `02` would need to fetch that inbox with http and upsert on salesforce wich are 2 different things.

Eventually doing this would lead to split job `02` in 2 more jobs: one for fetching OpenFn inbox (and saving on state), one for taking state and upserting on SF, which is what we do already with our 2 current jobs.

**Comment by aleksa-krolls** [comment]
@lakhassane new flow is working beautifully, thank you! 

@jedbgold fyi, I've updated the jobs on prod so that job `02` now has a message filter trigger.
