### ISSUE TITLE
Upsert fails with CNPJ externalId 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/itau-social#3]
## Bug
When testing #1 - Upsert operations in job `02` are failing in Salesforce with the error `NOT_FOUND: The requested resource does not exist` ([see run here](https://www.openfn.org/projects/2983/runs/10213177)) even though the mappings are correct and I _know_ this record exists in Salesforce. 

I came across a similar Salesforce issue before, and I think this error is thrown **because we have special characters like `/` in our external Id `CNPJ__c` used to upsert Account records**. Because of the special characters `CNPJ__c` is not being read correctly. 
https://github.com/OpenFn/itau-social/blob/d3dc8a22340f7160520daafad07725ecc2f80019/jobs/02-Update-Account-in-SF.js#L69

## Request
Please either...
1. Determine if there is a way to format the `CNPJ__c` so that we can continue to use it as the external Id for upserts, **OR**
2. Consider an alternative approach where in the initial state for job `01`, we receive the Salesforce record `Id` for the triggering record (see below). If we can pass this `Id` from L12 of the initial state to job `02` state --> then we can use `Id` for upserts instead of `CNPJ__c`

https://github.com/OpenFn/itau-social/blob/d3dc8a22340f7160520daafad07725ecc2f80019/sampleData/payload.json#L9-L12

**Comment by lakhassane** [comment]
Hm @aleksa-krolls about option 2. If we want to consider that, we might also want to save that `Id` to Salesforce.

Then having something like this might help:
```
alterState(state => {
  if (dataValue('$.objeto.cnpj')(state)) {
    return upsert(
      'Account',
      'Id',
      fields(
        field(Id, dataValue('Id')(state), // After saving it on state
       ...
      )
    )(state);
  }
  return state;
});
```

**Comment by aleksa-krolls** [comment]
@lakhassane `Id` is a Salesforce id, so it sounds like this might work? How the flow goes...
1. Salesforce sends to OpenFn the `sample_data/payload.json` (this includes Account `Id` and `CNPJ__c`)
2. OpenFn searches BU by `CNPJ__c` and then updates the `Account` record using ________ external Id (this could be either `Id` or `CNPJ__c` ... so if we can successfully pass `Id` from job `01` state --> job `02`, then let's we can definitely use `Id` to map back to Salesforce).
