### ISSUE TITLE
Change status values based on BU response

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/itau-social#5]
## Background, context, and business value

In issue #1 we requested that `01-getCNPJ.js` return a successful status (`state.data.status = 'Concluída'`) if the request to Base Unica received a `200` response. However, we are finding BU will sometimes respond with a `200` code even when the request has `Invalid parameters` (so this is actually not a successful sync). 

As an example, run `01-getCNPJ.js` with `sample_data/cnpj_notValid.json`. You will see BU responds with `Invalid Parameters`...
```
"data": {
    "idRequisicao": 23099,
    "codigo": 200,
    "mensagem": "Invalid parameters",
    "status": "Concluída"
  },
```

## The specific request, in as few words as possible

Please change the logic for how we set `status` in job `01-getCNPJ.js` so that...
1. If the BU response contains `"codigo": 200` and `"objeto":{...}` --> return `state.data.status = 'Concluída'` (success because there is data to send back to SF)
2. If the BU response contains `"codigo": 200` and NO `"objeto":{...}` --> return `state.data.status = 'Falha'` (failure because there is no data to send back to SF)
3. If the BU response contains `"codigo": 400` --> return `state.data.status = 'Falha'` (failure because BU throws an error and no data to send back to SF)

## state.json
`sample_data/cnpj_notValid.json`

1. Base Unica: Itau Social Base Unica Credentials can be found in lastpass by searching "Base Unica Testing (Itau Social)"
2. Salesforce sandbox: See LP for "Itau Social Salesfoce"

## adaptor

`language-http` for job `01`

## expression.js

`01-getCNPJ.js`

## output.json

See the specific request. To test...
1. `sample_data/payload.json` should return `state.data.status = 'Concluída'`
2. `sample_data/cnpj_notValid.json` should return `state.data.status = 'Falha'`

### side effects

1. Job `02` will upsert `Account` in Salesforce where `Sync_Status__c` is set to this `status` (determined based on BU response to job `01`)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 This is not working. When I run the job `01` for `cnpj_notValid.json` --> this returns `"status": "Concluída"`. I expect `"Falha"` because there is the `Invalid parameters` message and no `objeto` present. _Also,_ I run job `02` with this response... nothing happens ([see blank run](https://www.openfn.org/projects/2983/runs/10217285)). 
```
"data": {
    "idRequisicao": 23115,
    "codigo": 200,
    "mensagem": "Invalid parameters",
    "status": "Concluída"
  },

**Comment by taylordowns2000** [comment]
@aleksa-krolls , is this still not working or was it `git pull` related?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Closing now. Issue was related to `git pull` and `upsertIf` logic that was not updating the Account record if no `objeto` returned. Everything is working now with your latest changes, thank you! Pending client UAT feedback now.
